# Generated by Django 3.2.7 on 2021-11-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='SOME STRING', max_length=1000)),
                ('answer', models.TextField(default='SOME STRING', max_length=1000)),
            ],
        ),
    ]
