# Generated by Django 3.2.7 on 2021-11-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='images/')),
                ('judul', models.CharField(max_length=300)),
                ('isi', models.TextField()),
            ],
        ),
    ]
