# Generated by Django 3.2.7 on 2021-11-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaUDD', models.CharField(max_length=100)),
                ('alamatUDD', models.CharField(max_length=100)),
                ('nomorUDD', models.CharField(max_length=100)),
                ('goldar', models.CharField(max_length=100)),
                ('JumlahStok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StokAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaUDD', models.CharField(max_length=100)),
                ('alamatUDD', models.CharField(max_length=100)),
                ('nomorUDD', models.CharField(max_length=100)),
                ('goldar', models.CharField(max_length=100)),
                ('JumlahStok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StokB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaUDD', models.CharField(max_length=100)),
                ('alamatUDD', models.CharField(max_length=100)),
                ('nomorUDD', models.CharField(max_length=100)),
                ('goldar', models.CharField(max_length=100)),
                ('JumlahStok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StokO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaUDD', models.CharField(max_length=100)),
                ('alamatUDD', models.CharField(max_length=100)),
                ('nomorUDD', models.CharField(max_length=100)),
                ('goldar', models.CharField(max_length=100)),
                ('JumlahStok', models.IntegerField()),
            ],
        ),
    ]
