# Generated by Django 3.2.7 on 2021-12-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendonor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendonor',
            name='bukti_swab_negatif',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pendonor',
            name='bukti_swab_positif',
            field=models.CharField(max_length=100),
        ),
    ]
