# Generated by Django 3.2.7 on 2021-11-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id', models.CharField(max_length=127, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('nama', models.CharField(max_length=63, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UDD',
            fields=[
                ('nama', models.CharField(max_length=63, primary_key=True, serialize=False)),
                ('stock_A', models.PositiveIntegerField(default=0)),
                ('stock_B', models.PositiveIntegerField(default=0)),
                ('stock_O', models.PositiveIntegerField(default=0)),
                ('stock_AB', models.PositiveIntegerField(default=0)),
                ('kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cariDonor.kota')),
            ],
        ),
        migrations.AddField(
            model_name='kota',
            name='provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cariDonor.provinsi'),
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goldar', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cariDonor.kota')),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cariDonor.provinsi')),
            ],
        ),
    ]
